kind: pipeline
name: default

trigger:
  event:
    exclude: [promote]

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: build
    image: node
    volumes:
      - name: cache
        path: /drone/src/node_modules
      - name: nginx
        path: /drone/src/nginx
    commands:
      - yarn
      - yarn clean
      - yarn build
    environment:
      GATSBY_APP_BACKEND_URL:
        from_secret: GATSBY_APP_BACKEND_URL
      GATSBY_EXPERIMENTAL_ROUTING_APIS:
        from_secret: GATSBY_EXPERIMENTAL_ROUTING_APIS
  - name: deploy
    image: alpine
    volumes:
      - name: nginx
        path: /drone/src/nginx
    commands:
      - ls
      - ls nginx
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache/linceo.today
  - name: nginx
    host:
      path: /var/www/linceo.today
